#!/bin/sh

# Copyright 2006-2007 Kevin Reid, under the terms of the MIT X license
# found at http://www.opensource.org/licenses/mit-license.html ................

set -e

rm -rf compiled-lib/*
rm -f e-image-main e-image-run \
      test-parse-cache-*.sexp \
      {lisp,e-core}/*.{fasl,dfsl,nfasl,fas,lib,cls,x86f,abcl}

(cd antlr && ./clean.sh)
